version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      
    ports:
      - "5433:5432"
    networks:
      - pgadmin-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - pgadmin-network
    volumes:
      - /home/lamnv/Documents/class project/webEservise

networks:
  pgadmin-network:
    driver: bridge
